### ISSUE TITLE
Save image error in Jupyter notebook tutorial for Layer 2/3 EM images

### ISSUE THREAD

**Issue by shandran** [ceesem/ImageryClient#3]
Hello,
I am attempting to run the tutorial notebook [“Image and Segmentation Download”](https://github.com/AllenInstitute/MicronsBinder/blob/master/notebooks/intro/ImageAndSegmentationDownload.ipynb) from MicronsBinder on github. Everything in the notebook works fine until the code at the end to save the images. The error message returned is:

imageryclient.imagery.save_image_slices() argument after ** must be a mapping, not tuple

I have placed a copy of the notebook with the error here on my github repo: 
https://github.com/shandran/layer23volume/blob/main/mitochondria_analytics/debug/ImageAndSegmentationDownload_save_image_error.ipynb

The python environment I’m using is micronsbinder from here: 
https://github.com/seung-lab/MicronsBinder)

I did have to pip install imageryclient separately, which is the current version of 1.01. I’m wondering if some syntax or library has changed since the code was originally written and now this line no longer works. Any advice or assistance would be greatly appreciated!

Thanks,
Shawn

**Comment by ceesem** [comment]
This turned out to be a small but impactful typo. I just pushed a new patch (v1.0.2) to PyPi that fixes this, and your notebook now works for me.

Thanks for passing along the notebook, that was helpful.

**Comment by shandran** [comment]
That fixed it, thank you!
